### ISSUE TITLE
[Bug]: geocode metadata fails

### ISSUE THREAD

**Issue by taliboliver** [opera-adt/COMPASS#110]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When generating gslcs with geocoded metadata get the following error:

```python traceback
journal: s1_rdr2geo burst successfully ran in 0:04:09 (hr:min:sec)
journal: Starting s1_geocode_metadata burst
Traceback (most recent call last):
  File "/mnt/aurora-r0/cabrera/software/tools/COMPASS/src/compass/s1_cslc.py", line 54, in <module>
    main()
  File "/mnt/aurora-r0/cabrera/software/tools/COMPASS/src/compass/s1_cslc.py", line 49, in main
    run(parser.run_config_path, parser.args.grid_type)
  File "/mnt/aurora-r0/cabrera/software/tools/COMPASS/src/compass/s1_cslc.py", line 43, in run
    s1_geocode_slc.run(cfg)
  File "/mnt/aurora-r0/cabrera/software/tools/COMPASS/src/compass/s1_geocode_slc.py", line 102, in run
    s1_geocode_metadata.run(cfg, burst, fetch_from_scratch=True)
  File "/mnt/aurora-r0/cabrera/software/tools/COMPASS/src/compass/s1_geocode_metadata.py", line 73, in run
    geo.lines_per_block = blocksize
AttributeError: 'isce3.ext.isce3.geocode.GeocodeFloat32' object has no attribute 'lines_per_block'
```

### What did you expect?

I expected geocoded metadata

### Reproducible steps

```bash
1. A sample config file for one burst can be found from 
2. /mnt/aurora-r0/cabrera/data/compass_test/stack/runconfigs/geo_runconfig_20210725_t013_026557_iw2.yaml
3. ran by doing ./stack/run_files/run_20210725_t013_026557_iw2.sh
...
```

### Environment

```bash
- Using COMPASS 0.1.3
- isce3 0.10.0 from conda
...
```

**Comment by vbrancat** [comment]
@LiangJYu is this related the the block min/max changes in the geocode module? If yes, they should be solved with the next conda release, correct?

**Comment by LiangJYu** [comment]
> @LiangJYu is this related the the block min/max changes in the geocode module? If yes, they should be solved with the next conda release, correct?

@vbrancat This is related the min/max block size issue. [conda isce3 v0.10](https://github.com/isce-framework/isce3/blob/0b1acf6a5d64f7dcbd8e215d136963bafaafae6c/python/extensions/pybind_isce3/geocode/GeocodeCov.cpp#L104-L107) replaced `lines_per_block` with `min/max_block_size`.

This escapes the unit tests because we've disabled [rdr2geo processing](https://github.com/opera-adt/COMPASS/blob/9590be49916548afe79e805d2c2ccecade5df710/tests/data/geo_cslc_s1_template.yaml#L20).

I will submit a PR to fix.

@taliboliver Nice find!

**Comment by taliboliver** [comment]
Thanks for the quick follow up @vbrancat  and @LiangJYu !
