### ISSUE TITLE
The runconfigs take a list of orbit files but only uses the directory of first file [Bug]: 

### ISSUE THREAD

**Issue by gshiroma** [opera-adt/COMPASS#54]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The CLSC runconfigs take a list of orbit files (see example [here](https://github.com/opera-adt/COMPASS/blob/fcdd8ee23093934df99c3ac07a404f62a4c02000/src/compass/schemas/s1_cslc_radar.yaml#L12)), but only uses the directory of the first [orbit file](https://github.com/opera-adt/COMPASS/blob/fcdd8ee23093934df99c3ac07a404f62a4c02000/src/compass/utils/runconfig.py#L166). This issue was probably introduced because of [this S-1 reader PR](https://github.com/opera-adt/s1-reader/pull/71) merged to the main branch.

### What did you expect?

If the runconfig field accepts a list of orbit files, we should use that list to look for the orbit.

### Reproducible steps

```bash
-
```

### Environment

```bash
-
```

**Comment by vbrancat** [comment]
@yunjunz this is the inconsistency I pointed out in our latest meeting. What do you think? I'd like to respect what the schema/runconfig says and so this requires to have the old function in the `s1-reader` that correlates the orbit file.

**Comment by seongsujeong** [comment]
I think we need additional work on `s1-reader`. I am thinking about
1. Modify `from s1reader.s1_orbit.get_orbit_file_from_dir()` to take the list of files (and change the function name accordingly)
2. Add a function that takes in the orbit directory, and returns the list of orbit files in the directory

The new procedure would work like:
- If the list of the orbit file is provided, we directly call the function in `1`
- If the directory is provided, we get the orbit file list using the function in `2`, and pass that to `1`

Let me know what you think.

**Comment by gshiroma** [comment]
Thank you @vbrancat and @seongsujeong . 

@seongsujeong , to be more general, I think the user could provide a list of directories too or mixed. I think we could iterate over the runconfig orbit items and create a single (longer) list of orbit files. If the item a directory, we use your point `2` to add to the list of files for that directory. Then, when we have the list of files (with all directories converted into files) we can call function `1`.

**Comment by gshiroma** [comment]
@vbrancat , the runconfig provides a field with type field. How can you force it to be a list of files or a string of a directory? Maybe a list of a single element for the directory otherwise it will raise an error?

**Comment by vbrancat** [comment]
@seongsujeong will you take care of this?

**Comment by seongsujeong** [comment]
@vbrancat @gshiroma I'm on it. Please expect a PR on `s1-reader`. I'll add both of you (as well as @LiangJYu and @yunjunz ) as reviewers.

**Comment by gshiroma** [comment]
Thank you, @seongsujeong

**Comment by yunjunz** [comment]
Why don't we modify the runconfig to take the orbit directory (as one str) directly?

**Comment by gshiroma** [comment]
Uhm. What if the directory contains files that we don't want to be considered, e.g. lower resolution orbit files?

**Comment by gshiroma** [comment]
Or if the directory contains a long list of files and we know which one to use. BTW, the option to use the directory will still be there.

**Comment by yunjunz** [comment]
I assume you meant the restituted orbit or precise orbit? We could always search and prefer ethe precise version if it exsits. This is not in the current `s1reader` yet, but it's easy to add.

> Or if the directory contains a long list of files and we know which one to use. BTW, the option to use the directory will still be there.

It's pretty fast to search and grab, compared with other processing steps. And the use of directory can be the same for different dataset, which is convenient on the user side.

**Comment by gshiroma** [comment]
Well, not necessarily the user wants the better orbit. Maybe he wants the lower-resolution orbit for testing or comparison.
He will still have the option to provide a directory, if he prefers to do so.

**Comment by yunjunz** [comment]
I would say those are advanced users/developers (and a small portion), they know how to do that manually, e.g., use a different directory where there are only restituted orbits. And the dir in runconfig still supports that.

**Comment by gshiroma** [comment]
Well, they are probably advanced just by trying to run these workflows lol.

If we can provide that feature, why not? I mean, he can still provide a directory if he wants.

**Comment by yunjunz** [comment]
sorry, I meant to say: I don't see a case where specifying a directory only won't work, including your example above, so I don't see the benefit of adding more complex support, which is totally fine, except that two different styles of inputs might be confusing to some users.

**Comment by LiangJYu** [comment]
I think only the 2 following options for orbit input should be allowed:
1. single orbit file since this what PGE is expecting and they are for the foreseeable future the primary user.
2. directory containing orbit files to make usage easier for other users

`orbit_directory_path` should be added to the schema clearly reflect the options above and `orbit_file_path` can actually be a file path.  The following changes runconfig.py should account for the 2 options:
```python
def load_validate_yaml(...):
    ...
    # not 100% on this. I probably missed somethings ¯\_(ツ)_/¯ 
    if orbit_file is None and orbit_directory is None:
        raise error
    ...

def runconfig_to_bursts(...):
    ...
    # make orbit file default method since PGE is primary user
    if cfg.orbit_file_path is not None:
        orbit_path = cfg.orbit_file
    else:
        orbit_path = load_orbit_from_file(cfg.orbit_directory_path)
    ...
    load_bursts(..., orbit_path, ...)
    ...
```

I think a list of files is redundant if the option for a single orbit directory is allowed since a directory is already a collection of files. Anything else (list of files, directories, or the mix) to me is an excessive expectation of our runconfig to account for some arbitrary file/directory organization (or lack thereof).

**Comment by yunjunz** [comment]
Here is a summary of our discussions offline today, for reference:
1. the `s1reader` should have both capabilities: getting orbit file from both a) list of orbit files, and b) the orbit directory. 
2. the runconfig file should have one style only, for clarify; and a string for the orbit file is preferred, for the traceability and re-producebility.
3. the sweet spot for both 1 and 2 could be: on examples and comments for the runconfig file, we stick with 2) strictly, which is what will be delivered to SDS; on the code implementation, we could support both (a string for the orbit file or for the orbit directory), so that a directory will also work.
4. for future development, we should have a script to generate these runconfig files automatically, so that we do not need to write out the orbit file and safe file in a tedious way.

**Comment by vbrancat** [comment]
@seongsujeong and @gshiroma has this issue been solved? I think we merged a PR on the `s1-reader` to solve this.

**Comment by seongsujeong** [comment]
@vbrancat Yes, `s1_orbit.py` was revised. See [this PR](https://github.com/opera-adt/s1-reader/pull/79) in `s1-reader`.

**Comment by vbrancat** [comment]
Closed as it has been solved by https://github.com/opera-adt/s1-reader/pull/79
